# NumPy arrays

In [10]:
# numpy makes use of low-level libraries for working with vector and matrices such as
# Linear Algebra Subprograms (BLAS) and the Linear Algebra Package (LAPACK)
import numpy as np

# int array
ary = np.array([1, 2, 3, 4])
print(ary)
print(ary.dtype)

[1 2 3 4]
int64


In [7]:
# float array
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [12]:
# change array type
arr = np.array([2, 3, 5, 7])
print(arr)
print(arr.dtype)
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)

[2 3 5 7]
int64
[2. 3. 5. 7.]
float64


In [19]:
# element access: arr[i]
ary = np.array([0, 2, 4, 6])
print(ary[0])
print(ary[1])

0
2


In [23]:
# slicing too: arr[start:stop:step]
futatsu = ary[:2]
print(futatsu)
suri_x = ary[1::2]
print(suri_x)

[0 2]
[2 6]


In [32]:
# array arithmetics
arr_0 = np.array([2, 5, 7, 3])
arr_1 = np.array([5, 3, -9, 8])
print('2 * arr_1 =', 2 * arr_1)
print('arr_0 + arr_1  =', arr_0 + arr_1)
print('arr_0 - arr_1  =', arr_0 - arr_1)
print('arr_0 * arr_1  =', arr_0 * arr_1)
print('arr_0 / arr_1  =', arr_0 / arr_1)
print('arr_1 ** arr_0 =', arr_0 - arr_1)

2 * arr_1 = [ 10   6 -18  16]
arr_0 + arr_1  = [ 7  8 -2 11]
arr_0 - arr_1  = [-3  2 16 -5]
arr_0 * arr_1  = [ 10  15 -63  24]
arr_0 / arr_1  = [ 0.4         1.66666667 -0.77777778  0.375     ]
arr_1 ** arr_0 = [-3  2 16 -5]


In [33]:
# create array of numbers at regular intervals
np.linspace(0, 1, 5)  # (start, inclusive_end, n_elem)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.arange(0, 1, 0.3)  # (start, end, step)

array([0. , 0.3, 0.6, 0.9])

In [36]:
# higher dimensional arrays
mat = np.array([[3, 4], [7, 6]])
vec = np.array([1, 2])
print(mat.shape)  # the number of element in the shape tuple in the number of dimensions
print(vec.shape)  # the values of the elements are the number of elements inside each dimension (each nested array)

(2, 2)
(2,)


In [37]:
# reshape to flat array
mat.reshape(4,)

array([3, 4, 7, 6])

In [55]:
# dimensions can also be checked this way:
mat.ndim

2

In [45]:
# higher dimensional arrays
mat1 = [[1, 2], [3, 4]]
mat2 = [[5, 6], [7, 8]]
mat3 = [[9, 10], [11, 12]]
arr_3d = np.array([mat1, mat2, mat3])
print(f'arr_3d =\n{arr_3d}')
print('arr_3d.shape:', arr_3d.shape)

arr_3d =
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
arr_3d.shape: (3, 2, 2)


In [47]:
# access an element in a multi-dimensional array
print(mat)
mat[1, 0]

[[3 4]
 [7 6]]


7

In [48]:
# also supports slicing
mat[:, 0]  # all members of a single column (0th column)

array([3, 7])

# Matrices

In [51]:
# identity matrix
np.eye(3)  # np.identity(3) also works

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# transpose of a matrix
mat = np.array([[1, 2], [3, 4]])
print(mat.transpose())
print(mat.T)  # object property that returns the transpose

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [54]:
# trace of a matrix: the sum of the elements along the leading diagonal
mat.trace()

5

In [56]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 1], [0, 1]])
A @ B  # matrix multiplication operator= @

array([[-1,  3],
       [-3,  7]])

In [57]:
# keep in mind this is different from component-wise multiplication:
A * B

array([[-1,  2],
       [ 0,  4]])

In [62]:
# the Identity Matrix is a neutral element under matrix multiplication
A = np.array([[2, 3], [5, 7]])
I = np.eye(2, dtype=np.int64)  # identity matrix of ints (otherwise it would be floats)
A @ I

array([[2, 3],
       [5, 7]])

In [64]:
# Determinants and Inverses
from numpy import linalg

# Determinant: a scalar value that is a function of the entries of a square matrix
# It allows characterizing some properties of the matrix and the linear map represented by the matrix
linalg.det(A)  

-0.9999999999999987